version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: personal_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5422:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - personal-portal-network
  app:
    container_name: personal-portal-be
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/personal_portal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      CORS_ALLOWED_ORIGINS: "*"
    networks:
      - personal-portal-network

volumes:
  postgres_data:

networks:
  personal-portal-network:
    external: true
