version: '3.8'
services:
  db:
    image: postgres:15
    container_name: personal-portal-db
    environment:
      POSTGRES_DB: personal_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5422:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - personal-portal-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit:latest
    container_name: personal-portal-mailpit
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    networks:
      - personal-portal-network
    restart: unless-stopped

  app:
    container_name: personal-portal-be
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      mailpit:
        condition: service_started
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/personal_portal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      CORS_ALLOWED_ORIGINS: "http://localhost:8080"
      SPRING_MAIL_HOST: mailpit
      SPRING_MAIL_PORT: 1025
      SPRING_MAIL_USERNAME: ""
      SPRING_MAIL_PASSWORD: ""
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "false"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "false"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED: "false"
      SPRING_MAIL_FROM_EMAIL: "noreply@personal-portal.com"
      SPRING_MAIL_FROM_NAME: "Personal Portal"
    networks:
      - personal-portal-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  personal-portal-network:
    external: true
