version: '3.8'
services:
  db:
    image: postgres:15
    container_name: personal-portal-db
    environment:
      POSTGRES_DB: personal_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5422:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - personal-portal-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: personal-portal-be
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/personal_portal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      CORS_ALLOWED_ORIGINS: "http://localhost:8080"
    networks:
      - personal-portal-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  personal-portal-network:
    external: true
